# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

xcodeproj 'LoadingIndicatorExample/LoadingIndicatorExample.xcodeproj'
pod "DHLoadingIndicatorView", :path => "../"

# Uncomment the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end
